^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^start: Tue Jan 10 16:08:15 PST 2017
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
    from mpi4py import MPI
ImportError:     from mpi4py import MPI
ImportError    from mpi4py import MPI
ImportError: No module named mpi4py
No module named mpi4py
: No module named mpi4py
    from mpi4py import MPI
ImportError:     from mpi4py import MPI
No module named mpi4py
ImportError: No module named mpi4py
    from mpi4py import MPI
ImportError: No module named mpi4py
    from mpi4py import MPI
ImportError: No module named mpi4py
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: No module named mpi4py
ImportError: No module named mpi4py
ImportError: No module named mpi4py
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: No module named mpi4py
ImportError: No module named mpi4py
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: No module named mpi4py
ImportError: No module named mpi4py
    from mpi4py import MPI
ImportError: No module named mpi4py
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
Traceback (most recent call last):
  File "ME1_mpi.py", line 12, in <module>
    from mpi4py import MPI
ImportError: No module named mpi4py
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: No module named mpi4py
ImportError: No module named mpi4py
ImportError: No module named mpi4py
srun: error: sh-21-9: tasks 0-15: Exited with exit code 1
srun: error: sh-21-11: tasks 16-19: Exited with exit code 1
^^^^^^^end: Tue Jan 10 16:08:23 PST 2017
